services:
  - type: web
    name: evaluating-arithmetic-expressions-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT